# 기본 활성화된 룰 중에 비활성화할 룰을 지정
disabled_rules:
    - type_body_length
    - function_body_length
    - file_length
    - line_length
    - force_cast
    - force_try
    - duplicate_conditions
    - identifier_name
    - cyclomatic_complexity
    - redundant_optional_initialization

# 기본(default) 룰이 아닌 룰들을 활성화
opt_in_rules:
    - sorted_imports
    - direct_return
    - file_header
    - weak_delegate
